### ISSUE TITLE
Spannungsanzeige: Manchmal zeigt das RM-Modul falsche Spannungswerte an

### ISSUE THREAD

**Issue by Doumanix** [selfbus/software-arm-incubation#12]
Zum Beispiel 18,36mV - auch nach mehr als einem Tag Wartezeit.
Siehe clowns post: https://selfbus.forums3.com/post4063.html#p4063

**Comment by Doumanix** [comment]
@clown: um das Problem einzugrenzen ein paar Fragen.

1. 18,36 mV oder 18360 mV? 18,36 V klingt nach "irgendwo kommt ein Faktor 2 rein". 18,36 mV klingt nach einem seltsamen Faktor 2000.
2. kommt der falsche Wert immer bei demselben Modul? Oder demselben RM? Oder derselben RM-Modul-Variante? 

Sprich: kann man das Problem mit verschiedenen Modulen an demselben RM nachvollziehen oder mit verscheidenen RM und demselben Modul? Oder ist alles völlig sporadisch?

**Comment by clown-m** [comment]
@Doumanix 
Es sind 18,36mV.
Ja ich habe auch das Gefühl, das hier Bits verschluckt oder durch Rotation verändert werden werden.
Ich habe das Problem nur bei einigen Modulen, wie gesagt bei einem ist es sofort, bei zwei anderen bekomme ich nach 8-24 Std. einen korrekten Wert. Alle anderen sind ok, so bei 9xxx,y mV
Ich muss aber viele Boards noch überprüfen, habe viele unterschiedliche Fehler, einige Boards machen nach ein paar Stunden einen Testalarm funktionieren sonst aber einwandfrei.
Zur Zeit funktionieren 15 von 25 Boards ohne Probleme. Kann also sein, das hier noch ein paar Lötprobleme drin sind.
Aber keins der Boards behält die Daten, nach Busspannungswiederkehr sind alle Information wieder auf Null, zeigt eigentlich, das die Informationen nicht vom RM gelesen werden sondern die einzelne Aktion im Modul aufaddiert werden. Wenn ich einen Alarm auslese, dann sehe ich diese Meldung auch in den Werten. Was super klappt, alle Boards lesen auf Anhieb (nach dem ersten Zyklus) die Seriennummer des RM.  Werde später auch mal im Code schauen ob ich einen Anhaltspunkt finde

**Comment by StefanSverige** [comment]
In der ARM Geschichte bin ich bis auf die ersten Hardwareentwürfe für 
den RM nicht weiter aktive gewesen.

Ich gehe mal davon aus Ihr habt den Dual Q Melder. Da habe ich damals 
noch mit der LPC Version einige Tests gemacht und selbiges festgestellt. 
Irgendwie sendet der Dual Q nicht mehr oder besser nicht immer die 
Spannung. Nach einer gewissen Zeit scheint der das meistens zu machen. 
Wann der die Spannung sendet habe ich nicht herausfinden können.

Wir hatten damals die Theorie das die Spannung unter Last gemessen wird, 
also dann wenn die Rauchkammer LED getriggert wird um zu messen. Und 
dann scheint der da Irgendwie so etwas wie einen Mittelwert aus 
Ruhespannung und Lastspannung zu machen.

Um der Sache auf die Spur zu kommen hatte ich damals Versucht mit dem 
Funk Diagnosetool die Werte aus dem RM auszulesen. Leider stellte sich 
heraus das die neuen Funkmodule dabei Abstürzen und die Batterie leer 
saugen. Auf Nachfrage bei Gira warum man zu den Dual Q keine Verbindung 
bekommt meine ich eine Antwort bekommen zu haben die andeutet das die 
Dual Q (noch) nicht unterstützt werden. Stand aber vorher definitiv so 
auf der Homepage mit Link zum Diagnosetool.

Daher gehe ich davon aus das es nicht an den Platinen liegt, viel mehr 
am RM selbst. Bringt ein Tausch der Platine etwas, wandert das Problem 
mit der Platine oder bleibt es beim RM?

Man sollte auch noch bedenken das bei den Dual Q die Batterie immer den 
Controller versorgt, bei den Dual VDS war das noch anders, da wurde die 
Spannungsversorgung beim Einrasten hergestellt. Der Dual Q, zumindest 
die Revision die wir damals hatten, scheint sein Wakeup Signal an den 
Controller zu senden.

Wenn Ihr etwas findet, oder ich Helfen kann, lasst es mich wissen.
Dual Q and Dual VDS sollte ich noch im Regal haben.


/StefanSverige

**Comment by clown-m** [comment]
Hallo Stefan,
der Fehler ist mit dem Board gewandert, nachdem ich in einem zweiten RM getestet habe, also musste der Fehler auf dem Board sein. Ich konnte anscheinend das Problem mit den 18,36mV lösen, hatte beim ARM Chip auf einem Board mit großer Lupe noch einige Reste des Flussmittel entdeckt, nachdem ich das sauber gemacht habe, hat das Board den korrekten Wert angezeigt. Die anderen zwei Boards habe ich darauf hin auch noch mal gründlich sauber gemacht, und dann haben die es auch getan. Sorry war mein Fehler !

Wenn Du Dich aber so gut auskennst, kansst Du mir sagen wo die Statuswerte gespeichert werden, summiert der Dual Q  die Werte auf? Was passiert nach einem Power down des Dual Q (vom Sockel nehmen)? Falls der Dual Q die Werte aufsummiert, dann verstehe ich nicht warum diese nach einem Bus Power off/on alle wieder auf null sind? Oder gibt es hier noch ein Reset Problem, was macht der P02 (Pin 9) des RM? Interessant ist, das die Seriennummer immer korrekt übertragen wird, die Betriebsstunden aber nach dem Power cycle auf 0h ist, dachte das wäre der ausgelesene Wert?

Was meintest Du damit das der Dual Q IMMER den Controller mit Spannung versorgt? Wird das selfbus-RM-Board von der Batterie versorgt oder umgedreht, wenn ich die Schaltung richtig lese gehen die VCC 12V doch in Dual Q ?

**Comment by StefanSverige** [comment]
Das ist ineressant. Ich dachte beim ARM wird auch die Spannung noch vom 
RM abgefragt, macht das nun der ARM mit seinem ADC selber? Müsste ich 
mir im Code mal ansehen.

Die Statuswerte werden wenn im RM gespeichert, nicht im Controller. Da 
liegen die nur im RAM. So war das beim LPC und ich wüsste jetzt nicht 
warum das beim ARM erweitert worden seien sollte.

Es kann sehr gut sein das der ARM da noch nicht korrekt arbeitet. Die 
Software ist ja noch sehr neu und so richtig findet keiner Zeit sich die 
mal anzusehen. Ich für meinen Teil wollte das schon länger machen, muss 
mir dafür aber erst einmal einem ARM RM Platine besorgen.

Also bei den Betriebsstunden hatte ich immer Probleme mit dem Dual VDS, 
woran das lag habe ich nie herausgefunden. Ich meine das die Wete so vom 
RM kamen. Wie der Dual Q sich da verhält kann ich nicht sagen. Ebenso 
die Sache mit der Batteriespannung.

Ich meine mich erinnern zu können das über den zusätzlichen Pin erkannt 
wird wann der RM auf den Sockel kommt. Sprich damit der ARM weiss wann 
der RM abgefragt werden kann. Ich meine das wir mal den Fall hatten das 
der alte RM Abfragen mit einem Warnton quittiert hat wenn der nicht im 
Sockel war oder so. Das ist neu bei den letzten ARM Platinen.

Das Selfbus-Modul wird über den Bus versorgt, nur über den Bus. Es 
liefert auch eine Stützspannung, 12V, an den RM um durch die vielen 
Abfragen die Batterie nicht zu belasten. Aber der RM braucht immer seine 
Batterie, beim Q kann man die normal ja auch gar nicht mehr raus nehmen. 
Sprich RM und KNX sind galvanisch verbunden. Also keine 230V Sockel oder 
sonst etwas mit dran hängen!

Der Dual Q Melder versorgt seinen eigenen Controller immer mit Spannung, 
der dürfte nur schlafen wenn der RM nicht im Sockel ist. Ich meine das 
war beim Dual VDS noch anders.


/Stefan



Am 08.06.2019 um 15:34 schrieb clown-m:

**Comment by Doumanix** [comment]
Also wenns hilft, kam ich dir ja mal eine schicken ;)
Kannst mir ja mal im Forum ne PN schicken.

**Comment by clown-m** [comment]
Gibt es auch nach 5 Monaten noch keine neuen Erkentnisse?

**Comment by Doumanix** [comment]
Doch, die Diskussion ging im Forum weiter. 
Meine Meinung: funktioniert alles genau so wie beim LPC922  Modul.  
Wenn das sch*** Forum wieder ginge, könntest du es dort lesen.

**Comment by Doumanix** [comment]
Problem mit den zunächst falschen Spannungswerten ist offensichtlich kein Problem des Moduls sondern des RM selber. Nach einigen Stunden Laufzeit stimmen die Werte. 
Bevor das Thema ewig offen bleibt, mach ich es zu.
