### ISSUE TITLE
MultiSensorAktor: Eingang Pullup/Pulldown vertauscht?

### ISSUE THREAD

**Issue by maramend** [selfbus/software-arm-incubation#33]
**Ist Zustand:**

|Eingang | Schaltaktion   |
|---------|---------------|
|Pulldown|GND gegen IN|
|Pullup    |+3V3 gegen IN|

**Comment by Doumanix** [comment]
Test - Kommentar Webhook

**Comment by gnampf1** [comment]
Fixed in 549db4f
